export const locationInfo =

    {
        city:{id:'--',
            name:'--',
            coord:{
                lat:'--',
                lon:'--',
            },
            country:'--',
            population:'--',
            //more lines  
        },
        cnt:'--',
        cod:'--',
        list:[
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'00.00',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                    humidity:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },
            {
                dt:'--',
                dt_text:'--',
                main:{
                    temp:'--',
                    feels_like:'--',
                    temp_min:'--',
                    temp_max:'--',
                    pressure:'--',
                },
                pop:'--',
                rain:{
                    //3h :'--',
                },
                sys:{
                    pod:'--',
                },
                visiblility:'--',
                weather:[{
                    id:'--',
                    main:'--',
                    description:'--',
                    icon:'--',
                }],
                clouds:{
                    all:'--',
                },
                wind:{
                    speed:'--',
                    deg:'--',
                    gust:'--',
                },
                Object:'lines of code'
            },

        ]

    }
